language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - npm install
  - ./node_module/ibrik/bin/ibrik cover lib/**/*.coffee

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

after_success:
  - node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
