language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: './node_modules/ibrik/bin/ibrik cover lib/**/*.coffee curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

after_success:
  - cat coverage/lcov.info
  - node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
